server:
  port: 9001
spring:
  application:
    name: tx-lcn-service
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        instance-id: ${spring.application.name}