server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    # 服务注册
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        # 服务停止时取消注册
        deregister: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true
    # 网关配置
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
#            - PrefixPath=/auth-service
        - id: usercenter-service
          uri: lb://usercenter-service
          predicates:
            - Path=/usercenter-service/**
          filters:
            - StripPrefix=1
#            - PrefixPath=/usercenter-service
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule-service/**
          filters:
            - StripPrefix=1
#            - PrefixPath=/schedule-service
# 日志配置
logging:
  config: classpath:logback-config.xml