server:
  port: 8001
spring:
  application:
    name: usercenter-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/hui_cloud_uc?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 300000
      connection-test-query: select 1
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        # 服务停止时取消注册
        deregister: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true
# 日志配置
logging:
  config: classpath:logback-config.xml

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  type-aliases-package: com.hui.cloud.uc.entity
  global-config:
    banner: false
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1